### ISSUE TITLE
Allow dynamic configuration of endpoint urls

### ISSUE THREAD

**Issue by firstdoit** [vtex/node-vtex-api#12]
https://www.npmjs.com/package/nconf

**Comment by rdumont** [comment]
@firstdoit, I don't think this should be a part of the library. Each client should use its own way of tracking endpoints. Don't you agree?

**Comment by firstdoit** [comment]
@rdumont what's the use in having more than one way of configuring the endpoints for our API? The idea is that clients don't need to bother picking endpoints, but a developer may always override any settings with an env var.

**Comment by rdumont** [comment]
IMO, libraries should *never, ever* mess with environment variables, configuration files or any sort of magic. What is the problem with configuring endpoints programmatically, through the library API?

**Comment by firstdoit** [comment]
You're right. Ended up doing it directly on the toolbelt.
