### ISSUE TITLE
Error handling in Apps relink (patch)

### ISSUE THREAD

**Issue by luizerasmo** [vtex/node-vtex-api#52]
In the `relink` method in `Apps`, there is [no error-handling for the `archiver`](https://github.com/vtex/node-vtex-api/blob/master/src/Apps.ts#L111).

Maybe we should add something like [this](https://archiverjs.com/docs/#quick-start):
```
archive.on('error', function(err) {
  // do something
})
```

We believe this may have led to some recent `builder-hub` restarts when there was a missing file during `relink`, after we investigated the following error:
```
Error: ENOENT: no such file or directory, open '<filename>'
time="2018-08-07T20:14:19Z" level=fatal msg="Not a linked app and failed to start unrecoverably." error="App ended with exit code 1: exit status 1" 
```

**Comment by firstdoit** [comment]
Done!
